### ISSUE TITLE
Broken Link in the README

### ISSUE THREAD

**Issue by jonjoncronin** [jonjoncronin/data-structures#2]
@mcdonals Dude your link in the README resources is dead.

**Comment by mcdonals** [comment]
Strange. I tried following this "[GitHub](http://github.com)" markdown link format but apparently it automatically puts github.com in front of whatever you specify. If you removed the github portion manually it worked fine. I just switched to just a URL based on this github mastering markdown guide (https://guides.github.com/features/mastering-markdown/) and it now works fine.
